const User = require('../models/User');

// Create Super Admin user
exports.createSuperAdmin = async (req, res) => {
  try {
    const { username, password } = req.body;

    const userExists = await User.findOne({ username });
    if (userExists) {
      return res.status(400).json({ message: 'Username already exists' });
    }

    const user = await User.create({
      username,
      password,
      role: 'superadmin' // Force role
      // apiKey will be auto-generated by the pre-save hook
    });

    res.status(201).json({
      success: true,
      data: {
        id: user._id,
        username: user.username,
        role: user.role,
        apiKey: user.apiKey // Show API key once
      }
    });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};
