openapi: 3.0.0
info:
  title: Cricket Match API
  version: 1.0.0
  description: API for managing cricket matches, scores, and highlights.

tags:
  - name: CricketMatch
    description: Endpoints related to cricket matches

paths:
  /api/cricket-matches:
    post:
      tags: [CricketMatch]
      summary: Create a new cricket match
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                teamAId: { type: string }
                teamBId: { type: string }
                overs: { type: integer, enum: [6, 8, 10] }
                fixtureName: { type: string }
                captains:
                  type: object
                  properties:
                    teamA: { type: string }
                    teamB: { type: string }
                wicketKeepers:
                  type: object
                  properties:
                    teamA: { type: string }
                    teamB: { type: string }
      responses:
        "201":
          description: Match created

    get:
      tags: [CricketMatch]
      summary: Get all cricket matches
      responses:
        "200":
          description: List of matches

  /api/cricket-matches/{matchId}:
    get:
      tags: [CricketMatch]
      summary: Get match by ID
      parameters:
        - name: matchId
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Match found

    patch:
      tags: [CricketMatch]
      summary: Update cricket match
      parameters:
        - name: matchId
          in: path
          required: true
          schema: { type: string }
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Match updated

    delete:
      tags: [CricketMatch]
      summary: Delete cricket match
      parameters:
        - name: matchId
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Match deleted

  /api/cricket-matches/score:
    patch:
      tags: [CricketMatch]
      summary: Update player score in match
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                matchId: { type: string }
                playerId: { type: string }
                team: { type: string, enum: ["A", "B"] }
                runs: { type: number }
                wickets: { type: number }
                ballsFaced: { type: number }
                oversBowled: { type: number }
                extraBalls: { type: number }
      responses:
        "200":
          description: Score updated

  /api/cricket-matches/details/{matchId}:
    get:
      tags: [CricketMatch]
      summary: Get full match scorecard
      parameters:
        - name: matchId
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Full match stats

  /api/cricket-matches/{matchId}/highlight:
    post:
      tags: [CricketMatch]
      summary: Add highlight to match
      parameters:
        - name: matchId
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                over: { type: number }
                ball: { type: number }
                batsman: { type: string }
                bowler: { type: string }
                run: { type: number }
                isFour: { type: boolean }
                isSix: { type: boolean }
                isWicket: { type: boolean }
                wicketType: 
                  type: string
                  enum: [bowled, caught, runout, lbw, hitwicket, stumped, retired]
                fielder: { type: string }
                shotDirection: 
                  type: string
                  enum: [leg side, off side, cover, mid-wicket, square leg, third man, straight, point, long on, long off]
                extraType:
                  type: string
                  enum: [no ball, wide, bye, leg bye]
                commentary: { type: string }
      responses:
        "201":
          description: Highlight added