openapi: 3.0.0
info:
  title: Match API
  version: 1.0.0
  description: API for managing sports matches with full CRUD support.

servers:
  - url: /api
    description: Base API server

tags:
  - name: Matches
    description: Match resource operations

paths:
  /:
    get:
      tags:
        - Matches
      summary: Get all matches
      responses:
        "200":
          description: A list of matches
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatchList"
    post:
      tags:
        - Matches
      summary: Create a new match
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MatchInput"
      responses:
        "201":
          description: Match created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatchResponse"

  /{id}:
    get:
      tags:
        - Matches
      summary: Get a match by ID
      parameters:
        - $ref: "#/components/parameters/MatchId"
      responses:
        "200":
          description: Match found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatchResponse"
        "404":
          description: Match not found
    put:
      tags:
        - Matches
      summary: Replace a match
      parameters:
        - $ref: "#/components/parameters/MatchId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MatchInput"
      responses:
        "200":
          description: Match replaced
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatchResponse"
        "404":
          description: Match not found
    patch:
      tags:
        - Matches
      summary: Partially update a match
      parameters:
        - $ref: "#/components/parameters/MatchId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MatchInput"
      responses:
        "200":
          description: Match updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatchResponse"
        "404":
          description: Match not found
    delete:
      tags:
        - Matches
      summary: Delete a match
      parameters:
        - $ref: "#/components/parameters/MatchId"
      responses:
        "200":
          description: Match deleted
        "404":
          description: Match not found
    head:
      tags:
        - Matches
      summary: Check if a match exists
      parameters:
        - $ref: "#/components/parameters/MatchId"
      responses:
        "200":
          description: Match exists
        "404":
          description: Match not found

components:
  parameters:
    MatchId:
      name: id
      in: path
      required: true
      description: ID of the match
      schema:
        type: string

  schemas:
    MatchInput:
      type: object
      required:
        - sport
        - teamA
        - teamB
        - scheduledAt
      properties:
        sport:
          type: string
        teamA:
          type: string
          description: ObjectId reference to Team A
        teamB:
          type: string
          description: ObjectId reference to Team B
        pointsA:
          type: integer
          default: 0
        pointsB:
          type: integer
          default: 0
        scheduledAt:
          type: string
          format: date-time
        isComplete:
          type: boolean
          default: false
        result:
          type: string

    Match:
      allOf:
        - $ref: "#/components/schemas/MatchInput"
        - type: object
          properties:
            _id:
              type: string
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time

    MatchResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          $ref: "#/components/schemas/Match"

    MatchList:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: array
          items:
            $ref: "#/components/schemas/Match"
